#!/bin/bash
if [ $# -gt 1 ]; then
    echo 1>&2 "Usage: "$0" [file]"
    exit 1;
fi
if [ $# -eq 1 ]; then
    file=$1;
else
    file=-;
fi

#Wrong order in the output
#cat $file | cut -d: -f1,3 | sort -n -t: -k2

#Correct order using sed
cat $file | cut -d: -f1,3 | sed 'p' | paste -d: - - | cut -d: -f2,3 | sort -n

#Correct order using awk
#cat $file | cut -d: -f1,3 | sort -n -t: -k2 | awk -F: '{printf "%s:%s\n", $2, $1}'

